from pgvector.sqlalchemy import Vector as PGVector
"""add_process_status_table

Revision ID: 97dde6c91118
Revises: 001_initial_schema
Create Date: 2026-06-19 12:21:35.825031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97dde6c91118'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_statuses_user_id'), 'process_statuses', ['user_id'], unique=False)
    # Skip careerpilot_jobs cleanup - table does not exist in this schema version
    op.add_column('applications', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.add_column('applications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Manually create enum types before usage
    op.execute("CREATE TYPE application_status AS ENUM ('DRAFT', 'SUBMITTED', 'REVIEWING', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN')")
    op.execute("CREATE TYPE approval_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED')")
    op.execute("CREATE TYPE match_grade AS ENUM ('EXCELLENT', 'GOOD', 'FAIR', 'POOR')")
    op.execute("CREATE TYPE audit_action AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'GENERATE', 'SUBMIT')")
    op.execute("CREATE TYPE user_role AS ENUM ('CANDIDATE', 'RECRUITER', 'ADMIN')")

    op.execute("ALTER TABLE applications ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE applications ALTER COLUMN status TYPE application_status USING status::application_status")
    # Set default using the enum type name, ensuring quotes are handled
    op.execute("ALTER TABLE applications ALTER COLUMN status SET DEFAULT 'SUBMITTED'::application_status")
    op.drop_index(op.f('idx_applications_user'), table_name='applications')
    op.create_index(op.f('ix_applications_job_posting_id'), 'applications', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.drop_constraint(op.f('applications_resume_version_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_job_posting_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_cover_letter_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'job_postings', ['job_posting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'cover_letters', ['cover_letter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.drop_column('applications', 'confirmation_id')
    op.drop_column('applications', 'method')
    op.drop_column('applications', 'resume_version_id')
    op.drop_column('applications', 'applied_at')
    op.drop_column('applications', 'screenshot_before')
    op.drop_column('applications', 'screenshot_after')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("ALTER TABLE audit_logs ALTER COLUMN action TYPE audit_action USING action::audit_action")
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('idx_audit_logs_agent'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'agent_name')
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('companies', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.add_column('cover_letters', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('cover_letters', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('cover_letters', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cover_letters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cover_letters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('cover_letters', 'job_posting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.drop_constraint(op.f('cover_letters_job_posting_id_fkey'), 'cover_letters', type_='foreignkey')
    op.drop_constraint(op.f('cover_letters_user_id_fkey'), 'cover_letters', type_='foreignkey')
    op.create_foreign_key(None, 'cover_letters', 'job_postings', ['job_posting_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cover_letters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cover_letters', 'generated_at')
    op.add_column('job_postings', sa.Column('remote_type', sa.String(length=64), nullable=True))
    op.add_column('job_postings', sa.Column('employment_type', sa.String(length=64), nullable=True))
    op.add_column('job_postings', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('job_postings', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('skills_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('source_url', sa.String(length=1024), nullable=True))
    op.add_column('job_postings', sa.Column('source_platform', sa.String(length=64), nullable=True))
    op.add_column('job_postings', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('job_postings', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_postings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('job_postings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_postings', 'salary_min',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('job_postings', 'salary_max',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('job_postings', 'embedding',
               existing_type=sa.TEXT(),
               type_=PGVector(dim=384),
               existing_nullable=True,
               postgresql_using="embedding::vector(384)")
    op.drop_index(op.f('idx_job_postings_embedding'), table_name='job_postings', postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_job_postings_source'), table_name='job_postings')
    op.drop_index(op.f('idx_job_postings_status'), table_name='job_postings')
    op.drop_constraint(op.f('job_postings_hash_key_key'), 'job_postings', type_='unique')
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.drop_constraint(op.f('job_postings_company_id_fkey'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job_postings', 'source')
    op.drop_column('job_postings', 'url')
    op.drop_column('job_postings', 'discovered_at')
    op.drop_column('job_postings', 'hash_key')
    op.drop_column('job_postings', 'is_duplicate')
    op.drop_column('job_postings', 'status')
    op.add_column('match_scores', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.add_column('match_scores', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('match_scores', sa.Column('skills_score', sa.Float(), nullable=True))
    op.add_column('match_scores', sa.Column('experience_score', sa.Float(), nullable=True))
    op.add_column('match_scores', sa.Column('education_score', sa.Float(), nullable=True))
    op.add_column('match_scores', sa.Column('grade', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='match_grade', create_constraint=True), nullable=True))
    op.add_column('match_scores', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('match_scores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_match_scores_score_desc'), table_name='match_scores')
    op.drop_index(op.f('idx_match_scores_tier'), table_name='match_scores')
    op.drop_index(op.f('idx_match_scores_user'), table_name='match_scores')
    op.create_index(op.f('ix_match_scores_job_posting_id'), 'match_scores', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_match_scores_user_id'), 'match_scores', ['user_id'], unique=False)
    op.drop_constraint(op.f('match_scores_user_id_fkey'), 'match_scores', type_='foreignkey')
    op.drop_constraint(op.f('match_scores_job_posting_id_fkey'), 'match_scores', type_='foreignkey')
    op.create_foreign_key(None, 'match_scores', 'job_postings', ['job_posting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'match_scores', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'match_scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('match_scores', 'missing_skills_json')
    op.drop_column('match_scores', 'reasons_json')
    op.drop_column('match_scores', 'risk_indicators_json')
    op.drop_column('match_scores', 'tier')
    op.drop_column('match_scores', 'computed_at')
    op.drop_column('match_scores', 'score')
    op.add_column('pending_approvals', sa.Column('entity_type', sa.String(length=64), nullable=False))
    op.add_column('pending_approvals', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.add_column('pending_approvals', sa.Column('requested_action', sa.String(length=64), nullable=False))
    op.add_column('pending_approvals', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pending_approvals', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pending_approvals', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('pending_approvals', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('pending_approvals', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status', create_constraint=True),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('pending_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_pending_approvals_user_id'), 'pending_approvals', ['user_id'], unique=False)
    op.drop_constraint(op.f('pending_approvals_user_id_fkey'), 'pending_approvals', type_='foreignkey')
    op.drop_constraint(op.f('pending_approvals_resume_version_id_fkey'), 'pending_approvals', type_='foreignkey')
    op.drop_constraint(op.f('pending_approvals_cover_letter_id_fkey'), 'pending_approvals', type_='foreignkey')
    op.drop_constraint(op.f('pending_approvals_job_posting_id_fkey'), 'pending_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'pending_approvals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pending_approvals', 'job_posting_id')
    op.drop_column('pending_approvals', 'expires_at')
    op.drop_column('pending_approvals', 'cover_letter_id')
    op.drop_column('pending_approvals', 'resume_version_id')
    op.add_column('resume_versions', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('resume_versions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('resume_versions', sa.Column('file_path', sa.String(length=1024), nullable=True))
    op.add_column('resume_versions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('resume_versions', sa.Column('change_summary', sa.Text(), nullable=True))
    op.alter_column('resume_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.drop_constraint(op.f('resume_versions_resume_id_fkey'), 'resume_versions', type_='foreignkey')
    op.create_foreign_key(None, 'resume_versions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resume_versions', 'file_path_pdf')
    op.drop_column('resume_versions', 'job_posting_id')
    op.drop_column('resume_versions', 'version_type')
    op.drop_column('resume_versions', 'file_path_docx')
    op.add_column('resumes', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('file_type', sa.String(length=32), nullable=True))
    op.add_column('resumes', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_resumes_user'), table_name='resumes')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resumes', 'filename')
    op.drop_column('resumes', 'is_original')
    op.drop_column('resumes', 'uploaded_at')
    op.add_column('search_preferences', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('search_preferences', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('remote_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('employment_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('search_preferences', sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('search_preferences', sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_preferences', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('search_preferences', sa.Column('notify_on_match', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('search_preferences', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('search_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_search_preferences_user_id'), 'search_preferences', ['user_id'], unique=False)
    op.drop_constraint(op.f('search_preferences_user_id_fkey'), 'search_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'search_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('search_preferences', 'exclude_keywords_json')
    op.drop_column('search_preferences', 'locations_json')
    op.drop_column('search_preferences', 'roles_json')
    op.add_column('telegram_settings', sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('telegram_settings', sa.Column('digest_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('telegram_settings', sa.Column('reminder_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('telegram_settings', sa.Column('discovery_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('telegram_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('telegram_settings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.create_unique_constraint(None, 'telegram_settings', ['user_id'])
    op.drop_constraint(op.f('telegram_settings_user_id_fkey'), 'telegram_settings', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('telegram_settings', 'bot_token')
    op.drop_column('telegram_settings', 'allowed_user_id')
    op.drop_column('telegram_settings', 'notify_excellent_only')
    op.drop_column('telegram_settings', 'enabled')
    op.add_column('user_profiles', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('user_profiles', sa.Column('headline', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('user_profiles', sa.Column('github_url', sa.String(length=512), nullable=True))
    op.add_column('user_profiles', sa.Column('portfolio_url', sa.String(length=512), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_location', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_profiles', 'embedding',
               existing_type=postgresql.BYTEA(),
               type_=PGVector(dim=384),
               existing_nullable=True)

    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_profiles', 'raw_json')
    op.drop_column('user_profiles', 'parsed_at')
    op.add_column('users', sa.Column('role', sa.Enum('CANDIDATE', 'RECRUITER', 'ADMIN', name='user_role', create_constraint=True), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.add_column('user_profiles', sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'created_at')
    op.drop_column('user_profiles', 'preferred_roles')
    op.drop_column('user_profiles', 'preferred_location')
    op.drop_column('user_profiles', 'portfolio_url')
    op.drop_column('user_profiles', 'github_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'certifications')
    op.drop_column('user_profiles', 'education')
    op.drop_column('user_profiles', 'experience')
    op.drop_column('user_profiles', 'skills')
    op.drop_column('user_profiles', 'summary')
    op.drop_column('user_profiles', 'headline')
    op.drop_column('user_profiles', 'phone')
    op.drop_column('user_profiles', 'full_name')
    op.add_column('telegram_settings', sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('telegram_settings', sa.Column('notify_excellent_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('telegram_settings', sa.Column('allowed_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('telegram_settings', sa.Column('bot_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'telegram_settings', type_='foreignkey')
    op.create_foreign_key(op.f('telegram_settings_user_id_fkey'), 'telegram_settings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'telegram_settings', type_='unique')
    op.alter_column('telegram_settings', 'chat_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('telegram_settings', 'updated_at')
    op.drop_column('telegram_settings', 'created_at')
    op.drop_column('telegram_settings', 'discovery_enabled')
    op.drop_column('telegram_settings', 'reminder_enabled')
    op.drop_column('telegram_settings', 'digest_enabled')
    op.drop_column('telegram_settings', 'notifications_enabled')
    op.add_column('search_preferences', sa.Column('roles_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('search_preferences', sa.Column('locations_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["Ahmedabad", "Gandhinagar", "GIFT City", "Remote", "India", "International"]\'::jsonb'), autoincrement=False, nullable=True))
    op.add_column('search_preferences', sa.Column('exclude_keywords_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["Linux Administrator only", "Cybersecurity only", "Full Stack Developer"]\'::jsonb'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'search_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('search_preferences_user_id_fkey'), 'search_preferences', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_search_preferences_user_id'), table_name='search_preferences')
    op.alter_column('search_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('search_preferences', 'created_at')
    op.drop_column('search_preferences', 'notify_on_match')
    op.drop_column('search_preferences', 'is_active')
    op.drop_column('search_preferences', 'industries')
    op.drop_column('search_preferences', 'salary_max')
    op.drop_column('search_preferences', 'salary_min')
    op.drop_column('search_preferences', 'employment_types')
    op.drop_column('search_preferences', 'remote_types')
    op.drop_column('search_preferences', 'locations')
    op.drop_column('search_preferences', 'keywords')
    op.drop_column('search_preferences', 'name')
    op.add_column('resumes', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('is_original', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.create_index(op.f('idx_resumes_user'), 'resumes', ['user_id'], unique=False)
    op.alter_column('resumes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'is_active')
    op.drop_column('resumes', 'embedding')
    op.drop_column('resumes', 'parsed_text')
    op.drop_column('resumes', 'file_type')
    op.drop_column('resumes', 'title')
    op.add_column('resume_versions', sa.Column('file_path_docx', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resume_versions', sa.Column('version_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resume_versions', sa.Column('job_posting_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resume_versions', sa.Column('file_path_pdf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.create_foreign_key(op.f('resume_versions_resume_id_fkey'), 'resume_versions', 'resumes', ['resume_id'], ['id'])
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.alter_column('resume_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('resume_versions', 'change_summary')
    op.drop_column('resume_versions', 'embedding')
    op.drop_column('resume_versions', 'file_path')
    op.drop_column('resume_versions', 'content')
    op.drop_column('resume_versions', 'version_number')
    op.add_column('pending_approvals', sa.Column('resume_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pending_approvals', sa.Column('cover_letter_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pending_approvals', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('pending_approvals', sa.Column('job_posting_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pending_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('pending_approvals_job_posting_id_fkey'), 'pending_approvals', 'job_postings', ['job_posting_id'], ['id'])
    op.create_foreign_key(op.f('pending_approvals_cover_letter_id_fkey'), 'pending_approvals', 'cover_letters', ['cover_letter_id'], ['id'])
    op.create_foreign_key(op.f('pending_approvals_resume_version_id_fkey'), 'pending_approvals', 'resume_versions', ['resume_version_id'], ['id'])
    op.create_foreign_key(op.f('pending_approvals_user_id_fkey'), 'pending_approvals', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_pending_approvals_user_id'), table_name='pending_approvals')
    op.alter_column('pending_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pending_approvals', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status', create_constraint=True),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('pending_approvals', 'updated_at')
    op.drop_column('pending_approvals', 'review_notes')
    op.drop_column('pending_approvals', 'reviewed_at')
    op.drop_column('pending_approvals', 'context')
    op.drop_column('pending_approvals', 'requested_action')
    op.drop_column('pending_approvals', 'entity_id')
    op.drop_column('pending_approvals', 'entity_type')
    op.add_column('match_scores', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_scores', sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('match_scores', sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('match_scores', sa.Column('risk_indicators_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('match_scores', sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('match_scores', sa.Column('missing_skills_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'match_scores', type_='foreignkey')
    op.drop_constraint(None, 'match_scores', type_='foreignkey')
    op.drop_constraint(None, 'match_scores', type_='foreignkey')
    op.create_foreign_key(op.f('match_scores_job_posting_id_fkey'), 'match_scores', 'job_postings', ['job_posting_id'], ['id'])
    op.create_foreign_key(op.f('match_scores_user_id_fkey'), 'match_scores', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_match_scores_user_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_job_posting_id'), table_name='match_scores')
    op.create_index(op.f('idx_match_scores_user'), 'match_scores', ['user_id'], unique=False)
    op.create_index(op.f('idx_match_scores_tier'), 'match_scores', ['tier'], unique=False)
    op.create_index(op.f('idx_match_scores_score_desc'), 'match_scores', ['score'], unique=False)
    op.drop_column('match_scores', 'created_at')
    op.drop_column('match_scores', 'details')
    op.drop_column('match_scores', 'grade')
    op.drop_column('match_scores', 'education_score')
    op.drop_column('match_scores', 'experience_score')
    op.drop_column('match_scores', 'skills_score')
    op.drop_column('match_scores', 'overall_score')
    op.drop_column('match_scores', 'resume_id')
    op.add_column('job_postings', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('is_duplicate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('hash_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('discovered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_company_id_fkey'), 'job_postings', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.create_unique_constraint(op.f('job_postings_hash_key_key'), 'job_postings', ['hash_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_job_postings_status'), 'job_postings', ['status', 'discovered_at'], unique=False)
    op.create_index(op.f('idx_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_index(op.f('idx_job_postings_embedding'), 'job_postings', [sa.literal_column('(embedding::vector(384))')], unique=False, postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('job_postings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_postings', 'salary_max',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('job_postings', 'salary_min',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('job_postings', 'updated_at')
    op.drop_column('job_postings', 'created_at')
    op.drop_column('job_postings', 'expires_at')
    op.drop_column('job_postings', 'is_active')
    op.drop_column('job_postings', 'external_id')
    op.drop_column('job_postings', 'source_platform')
    op.drop_column('job_postings', 'source_url')
    op.drop_column('job_postings', 'skills_required')
    op.drop_column('job_postings', 'responsibilities')
    op.drop_column('job_postings', 'requirements')
    op.drop_column('job_postings', 'currency')
    op.drop_column('job_postings', 'employment_type')
    op.drop_column('job_postings', 'remote_type')
    op.add_column('cover_letters', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.create_foreign_key(op.f('cover_letters_user_id_fkey'), 'cover_letters', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cover_letters_job_posting_id_fkey'), 'cover_letters', 'job_postings', ['job_posting_id'], ['id'])
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.alter_column('cover_letters', 'job_posting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cover_letters', 'updated_at')
    op.drop_column('cover_letters', 'created_at')
    op.drop_column('cover_letters', 'is_approved')
    op.drop_column('cover_letters', 'word_count')
    op.drop_column('cover_letters', 'title')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'meta_data')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'description')
    op.add_column('audit_logs', sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_logs_agent'), 'audit_logs', ['agent_name'], unique=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'GENERATE', 'SUBMIT', name='audit_action', create_constraint=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'user_id')
    op.add_column('applications', sa.Column('screenshot_after', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('screenshot_before', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('resume_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('confirmation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('applications_cover_letter_id_fkey'), 'applications', 'cover_letters', ['cover_letter_id'], ['id'])
    op.create_foreign_key(op.f('applications_job_posting_id_fkey'), 'applications', 'job_postings', ['job_posting_id'], ['id'])
    op.create_foreign_key(op.f('applications_resume_version_id_fkey'), 'applications', 'resume_versions', ['resume_version_id'], ['id'])
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_posting_id'), table_name='applications')
    op.create_index(op.f('idx_applications_user'), 'applications', ['user_id'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWING', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status', create_constraint=True),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'submitted'::character varying"))
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'meta_data')
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'submitted_at')
    op.drop_column('applications', 'resume_id')
    op.create_table('careerpilot_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hash_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_job_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('posted_at', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('salary', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('employment_type', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('work_mode', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('experience_required', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('careerpilot_jobs_pkey')),
    sa.UniqueConstraint('hash_key', name=op.f('careerpilot_jobs_hash_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_careerpilot_jobs_source'), 'careerpilot_jobs', ['source'], unique=False)
    op.create_index(op.f('idx_careerpilot_jobs_hash'), 'careerpilot_jobs', ['hash_key'], unique=False)
    op.create_index(op.f('idx_careerpilot_jobs_embedding'), 'careerpilot_jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_process_statuses_user_id'), table_name='process_statuses')
    op.drop_table('process_statuses')
    # ### end Alembic commands ###
